[[plugins]]
package = "@netlify/plugin-local-install-core"

[[plugins]]
package = "./netlify-emailplugin"
    config:
      to: peter@flutterwavego.com
      from: raphael@flutterwavego.com
      message: We just deployed some bug fixes