[[plugins]]
package = "@netlify/plugin-local-install-core"

[[plugins]]
package = "./netlify-emailplugin"
    [plugins.inputs]
    from = "raphael@flutterwavego.com"
    to = "peter@flutterwavego.com"